version: '3.8'

services:
  app:
    build:
      context: ./src
      args:
        - DEV=true
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000