version: '3.8'

services:
  app:
    build:
      context: ./src
      args:
        - DEV=true
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=devdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d devdb -U devuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: